---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Welcome to Informatix Zone"
keywords:    "sharpoint, IT, QA, testing, automation, business processes"
description: "A landing page for information about informatix zone, a company offering IT consultancy services in Ireland"
source_link: "https://informatixzone.github.io"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#C5D9C8'
  blue:      '#49a7e9'
  green:     '#087515'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
